-- Active: 1714029462031@@baza.fmf.uni-lj.si@5432@sem2024_mihaj@public
GRANT ALL ON DATABASE sem2024_mihaj TO ninaj WITH GRANT OPTION;
GRANT ALL ON SCHEMA public TO ninaj WITH GRANT OPTION;
GRANT ALL ON ALL TABLES IN SCHEMA public TO ninaj WITH GRANT OPTION;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO ninaj WITH GRANT OPTION;

GRANT CONNECT ON DATABASE sem2024_mihaj TO javnost;
########################################################################

GRANT ALL PRIVILEGES ON DATABASE sem2024_mihaj TO javnost;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO javnost;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO javnost;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO javnost;

GRANT ALL PRIVILEGES ON DATABASE sem2024_mihaj TO ninaj;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ninaj;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ninaj;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ninaj;


--prihodnje pravice
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO ninaj;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO ninaj;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO ninaj;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO javnost;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO javnost;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO javnost;

-- javnost ne sme spreminjat tabel
REVOKE CREATE ON SCHEMA public FROM javnost;
